---
# Documentation:
# https://github.com/DSIN-INSA-Strasbourg/ansible-juniper-collection/blob/main/collections/ansible_collections/insa_strasbourg/juniper/docs/ex_config.md

ex_config_hostname: distribution-004
ex_config_location: CHANGE ME
ex_config_ipaddress: 192.168.250.4
ex_config_netmask: 255.255.255.0
ex_config_gateway: 192.168.250.254

# ex_config_poeenabled: false


ex_config_interfaces:
  - name: ge-0/0/0
    description: AP03
    poe: true
    vlans:
      - wifi

  - name: ge-0/0/1
    description: AP04
    poe: true
    vlans:
      - wifi

  - name: ge-0/0/2
    description: host-emp-003
    toip: true
    vlans:
      - employees

  - name: ge-0/0/3
    description: host-emp-004
    toip: true
    vlans:
      - employees

  - name: ge-0/0/4
    description: host-stu-003
    vlans:
      - students

  - name: ge-0/0/5
    description: host-stu-004
    vlans:
      - students

  - name: ge-0/0/6
    description: host-mgt-003
    toip: true
    vlans:
      - management

  - name: ge-0/0/7
    description: host-mgt-004
    toip: true
    vlans:
      - management

  - name: ge-0/0/8
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/9
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/10
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/11
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/12
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/13
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/14
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/15
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/16
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/17
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/18
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/19
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/20
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/21
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/22
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/23
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/24
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/25
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/26
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/27
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/28
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/29
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/30
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/31
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/32
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/33
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/34
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/35
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/36
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/37
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/38
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/39
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/40
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/41
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/42
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/43
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/44
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/45
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/46
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management

  - name: ge-0/0/47
    description:
    # toip: true
    # poe: true
    # native_vlan:
    # trunk: true
    trusted: true
    vlans:
      - management




  ###############################################
  # Ports SFP28 (1G:"ge" / 10G:"xe" / 25G:"et") #
  ###############################################
  - name: et-0/1/0
    description:
    disabled: true
    trunk: true
    trusted: true
    vlans:
      - all

  - name: et-0/1/1
    description:
    disabled: true
    trunk: true
    trusted: true
    vlans:
      - all

  - name: et-0/1/2
    description:
    disabled: true
    trunk: true
    trusted: true
    vlans:
      - all

  - name: et-0/1/3
    description:
    disabled: true
    trunk: true
    trusted: true
    vlans:
      - all





  ###################################
  # Ports SFP+ (1G:"ge" / 10G:"xe") #
  ###################################
  - name: xe-0/2/0
    description:
    disabled: true
    trunk: true
    trusted: true
    vlans:
      - all

  - name: xe-0/2/1
    description:
    disabled: true
    trunk: true
    trusted: true
    vlans:
      - all

  - name: xe-0/2/2
    description:
    disabled: true
    trunk: true
    trusted: true
    vlans:
      - all

  - name: xe-0/2/3
    description: datacenter-001
    trunk: true
    trusted: true
    vlans:
      - all
